services:
  school-map:
    build:
      context: ./school-map
      dockerfile: Dockerfile
    container_name: school-map
    volumes:
      - ./school-map:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true


networks:
  proxy-network:
    external: true